spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cinema;
    username: root
    password: root
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/master-test.xml

  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081

logging:
  config: classpath:logback/logback.xml