spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/cinema?useSSL=false&serverTimezone=Europe/Warsaw&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  liquibase:
    change-log: classpath:/db/master.xml

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false

logging:
  config: classpath:logback/logback.xml
