spring:

  datasource:
    url: jdbc:mysql://0.0.0.0:3306/production_cinema?serverTimezone=Europe/Warsaw
    username: production
    password: production
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false

logging:
  config: classpath:logback/logback.xml