<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://soap.restapp.tt.com.pl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ns1="http://localhost:8080/soap/movies"
                  name="MovieEndpointService"
                  targetNamespace="http://soap.restapp.tt.com.pl/">
    <wsdl:import location="indirectwsdl.wsdl" namespace="http://localhost:8080/soap/movies">
    </wsdl:import>
    <wsdl:binding name="MovieEndpointServiceSoapBinding" type="ns1:MoviesPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="createMovie">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="createMovie">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="createMovieResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="DatatypeConfigurationException">
                <soap:fault name="DatatypeConfigurationException" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getAllMovies">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getAllMovies">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getAllMoviesResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="DatatypeConfigurationException">
                <soap:fault name="DatatypeConfigurationException" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getMoviesById">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getMoviesById">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getMoviesByIdResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="DatatypeConfigurationException">
                <soap:fault name="DatatypeConfigurationException" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="updateMovie">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="updateMovie">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="updateMovieResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="deleteMovie">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="deleteMovie">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="deleteMovieResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MovieEndpointService">
        <wsdl:port binding="tns:MovieEndpointServiceSoapBinding" name="MovieEndpointPort">
            <soap:address location="http://localhost:8080/ws/moviesWS"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>